<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'System' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Symfony\\Component\\Routing\\' => array($vendorDir . '/symfony/routing'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Sabre\\VObject' => array($vendorDir . '/sabre/vobject/lib'),
    'Sabre\\HTTP' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\DAVACL' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\DAV' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\CardDAV' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\CalDAV' => array($vendorDir . '/sabre/dav/lib'),
    'Realestate\\MssqlBundle' => array($vendorDir . '/isoft/mssql-bundle'),
    'Pimple' => array($vendorDir . '/pimple/pimple/lib'),
    'Patchwork' => array($vendorDir . '/patchwork/utf8/class'),
    'OpenCloud' => array($vendorDir . '/rackspace/php-opencloud/lib', $vendorDir . '/rackspace/php-opencloud/tests'),
    'Normalizer' => array($vendorDir . '/patchwork/utf8/class'),
    'Net' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Math' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Hautelook' => array($vendorDir . '/hautelook/phpass/src'),
    'Guzzle\\Stream' => array($vendorDir . '/guzzle/stream'),
    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
    'Guzzle\\Http' => array($vendorDir . '/guzzle/http'),
    'Guzzle\\Common' => array($vendorDir . '/guzzle/common'),
    'GetId3_' => array($vendorDir . '/phansys/getid3'),
    'File' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Crypt' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
    'Archive_Tar' => array($vendorDir . '/pear/archive_tar'),
);
