language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.5.9
  - 5.5.10
  - 5.6

matrix:
  allow_failures:
    - php: 5.5.10
    - php: 5.6

script: phpunit --configuration tests/phpunit.xml

before_script: composer install
