docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - { Intro: intro.md }
    - Reference:
      - 'Standard Filters': standard-filters.md
      - 'Word Filters': word.md
      - 'File Filters': file.md
      - 'Filter Chains': filter-chains.md
      - 'String Inflection': inflector.md
      - 'Static Filter': static-filter.md
      - 'Writing Filters': writing-filters.md
site_name: zend-filter
site_description: Zend\Filter
repo_url: 'https://github.com/zendframework/zend-filter'
copyright: 'Copyright (c) 2016 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
