<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Sabre\\VObject' => array($vendorDir . '/sabre/vobject/lib'),
    'Sabre\\HTTP' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\DAVACL' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\DAV' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\CardDAV' => array($vendorDir . '/sabre/dav/lib'),
    'Sabre\\CalDAV' => array($vendorDir . '/sabre/dav/lib'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
);
