<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Zend_Xml' => array($vendorDir . '/zf1/zend-xml/library'),
    'Zend_Search_Lucene' => array($vendorDir . '/zf1/zend-search-lucene/library'),
    'Zend_Search' => array($vendorDir . '/zf1/zend-search/library'),
    'Zend_Exception' => array($vendorDir . '/zf1/zend-exception/library'),
    'Pimple' => array($vendorDir . '/pimple/pimple/src'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'OpenCloud' => array($vendorDir . '/rackspace/php-opencloud/lib', $vendorDir . '/rackspace/php-opencloud/tests'),
    'Guzzle\\Stream' => array($vendorDir . '/guzzle/stream'),
    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
    'Guzzle\\Http' => array($vendorDir . '/guzzle/http'),
    'Guzzle\\Common' => array($vendorDir . '/guzzle/common'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Doctrine\\Common\\' => array($vendorDir . '/doctrine/common/lib'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    'Assetic' => array($vendorDir . '/kriswallsmith/assetic/src'),
    'Archive_Tar' => array($vendorDir . '/pear/archive_tar'),
    '' => array($vendorDir . '/pear/pear-core-minimal/src'),
);
